# Generated by Django 6.0.4 on 2026-04-28 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='city',
        ),
        migrations.AddField(
            model_name='route',
            name='driver_name',
            field=models.CharField(default='سائق تكسي', max_length=64),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_phone',
            field=models.CharField(default='0770', max_length=15),
        ),
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='booked_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
